Repository eslint/create-config, pull requests merged in 2024-04, with the labels that each got.

#85 fix: add `log.warn`
  lib/utils/logging.js
Labels: bug

#88 chore: run `npm install` before npm publish
  .github/workflows/release-please.yml
Labels: chore

#92 fix: use eslint-config-airbnb-base by default
  lib/config-generator.js
  tests/__snapshots__/style-esm-none-airbnb
  tests/__snapshots__/style-esm-react-airbnb
  tests/config-snapshots.spec.js
Labels: bug

#94 fix: not install multi tseslint versions
  lib/config-generator.js
  tests/__snapshots__/style-esm-none-xo-typescript
Labels: bug, accepted

#103 docs: use @eslint/create-config latest
  README.md
Labels: documentation

#109 ci: run tests in Node.js 22
  .github/workflows/ci.yml
Labels: accepted, build

#108 feat: remove style guides
  README.md
  bin/create-config.js
  lib/config-generator.js
  tests/__snapshots__/config@eslint-config-airbnb
  tests/__snapshots__/config@eslint-config-airbnb-base
  tests/__snapshots__/config@eslint-config-standard
  tests/__snapshots__/config@eslint-config-standard-flat
  tests/__snapshots__/config@eslint-config-standard-flat2
  tests/__snapshots__/config@eslint-config-xo
  tests/__snapshots__/problems-commonjs-none-javascript
  tests/__snapshots__/problems-commonjs-none-typescript
  tests/__snapshots__/problems-commonjs-react-javascript
  tests/__snapshots__/problems-commonjs-react-typescript
  tests/__snapshots__/problems-commonjs-vue-javascript
  tests/__snapshots__/problems-commonjs-vue-typescript
  tests/__snapshots__/problems-esm-none-javascript
  tests/__snapshots__/problems-esm-none-typescript
  tests/__snapshots__/problems-esm-react-javascript
  tests/__snapshots__/problems-esm-react-typescript
  tests/__snapshots__/problems-esm-vue-javascript
  tests/__snapshots__/problems-esm-vue-typescript
  tests/__snapshots__/problems-script-none-javascript
  tests/__snapshots__/problems-script-none-typescript
  tests/__snapshots__/problems-script-react-javascript
  tests/__snapshots__/problems-script-react-typescript
  tests/__snapshots__/problems-script-vue-javascript
  tests/__snapshots__/problems-script-vue-typescript
  tests/__snapshots__/syntax-commonjs-none-javascript
  tests/__snapshots__/syntax-commonjs-none-typescript
  tests/__snapshots__/syntax-commonjs-react-javascript
  tests/__snapshots__/syntax-commonjs-react-typescript
  tests/__snapshots__/syntax-commonjs-vue-javascript
  tests/__snapshots__/syntax-commonjs-vue-typescript
  tests/__snapshots__/syntax-esm-none-javascript
  tests/__snapshots__/syntax-esm-none-typescript
  tests/__snapshots__/syntax-esm-react-javascript
  tests/__snapshots__/syntax-esm-react-typescript
  tests/__snapshots__/syntax-esm-vue-javascript
  tests/__snapshots__/syntax-esm-vue-typescript
  tests/__snapshots__/syntax-script-none-javascript
  tests/__snapshots__/syntax-script-none-typescript
  tests/__snapshots__/syntax-script-react-javascript
  tests/__snapshots__/syntax-script-react-typescript
  tests/__snapshots__/syntax-script-vue-javascript
  tests/__snapshots__/syntax-script-vue-typescript
  tests/config-snapshots.spec.js
Labels: feature, accepted

#111 chore: switch to eslint v9, eslint-config-eslint v10
  package.json
Labels: chore
