Repository eslint/create-config, pull requests merged in 2024-05, with the labels that each got.

#113 fix: use @eslint/compat to fix eslint v9 + react plugin
  lib/config-generator.js
  lib/utils/npm-utils.js
  tests/__snapshots__/config@eslint-config-airbnb
  tests/__snapshots__/config@eslint-config-airbnb-base
  tests/__snapshots__/config@eslint-config-standard
  tests/__snapshots__/config@eslint-config-standard-flat
  tests/__snapshots__/config@eslint-config-standard-flat2
  tests/__snapshots__/config@eslint-config-xo
  tests/__snapshots__/problems-commonjs-none-javascript
  tests/__snapshots__/problems-commonjs-none-typescript
  tests/__snapshots__/problems-commonjs-react-javascript
  tests/__snapshots__/problems-commonjs-vue-javascript
  tests/__snapshots__/problems-commonjs-vue-typescript
  tests/__snapshots__/problems-esm-none-javascript
  tests/__snapshots__/problems-esm-none-typescript
  tests/__snapshots__/problems-esm-react-eslint8.x-javascript
  tests/__snapshots__/problems-esm-react-eslint8.x-typescript
  tests/__snapshots__/problems-esm-react-eslint9.x-javascript
  tests/__snapshots__/problems-esm-react-eslint9.x-typescript
  tests/__snapshots__/problems-esm-react-javascript
  tests/__snapshots__/problems-esm-vue-javascript
  tests/__snapshots__/problems-esm-vue-typescript
  tests/__snapshots__/problems-script-none-javascript
  tests/__snapshots__/problems-script-none-typescript
  tests/__snapshots__/problems-script-react-javascript
  tests/__snapshots__/problems-script-vue-javascript
  tests/__snapshots__/problems-script-vue-typescript
  tests/__snapshots__/syntax-commonjs-none-javascript
  tests/__snapshots__/syntax-commonjs-none-typescript
  tests/__snapshots__/syntax-commonjs-vue-javascript
  tests/__snapshots__/syntax-commonjs-vue-typescript
  tests/__snapshots__/syntax-esm-none-javascript
  tests/__snapshots__/syntax-esm-none-typescript
  tests/__snapshots__/syntax-esm-react-eslint8.x-javascript
  tests/__snapshots__/syntax-esm-react-eslint8.x-typescript
  tests/__snapshots__/syntax-esm-react-eslint9.x-javascript
  tests/__snapshots__/syntax-esm-react-eslint9.x-typescript
  tests/__snapshots__/syntax-esm-react-javascript
  tests/__snapshots__/syntax-esm-vue-javascript
  tests/__snapshots__/syntax-esm-vue-typescript
  tests/__snapshots__/syntax-script-none-javascript
  tests/__snapshots__/syntax-script-none-typescript
  tests/__snapshots__/syntax-script-vue-javascript
  tests/__snapshots__/syntax-script-vue-typescript
  tests/config-snapshots.spec.js
Labels: bug

#117 test: replace esmock with sinon
  .npmrc
  package.json
  tests/utils/npm-utils.spec.js
Labels: chore

#115 ci: reduce list of releasable tags to `feat`, `fix` and `perf`
  .github/workflows/release-please.yml
Labels: build

#118 fix: use `--force` to install eslint v9 + tseslint
  lib/config-generator.js
  tests/__snapshots__/problems-commonjs-none-typescript
  tests/__snapshots__/problems-commonjs-vue-typescript
  tests/__snapshots__/problems-esm-none-typescript
  tests/__snapshots__/problems-esm-react-eslint8.x-typescript
  tests/__snapshots__/problems-esm-vue-typescript
  tests/__snapshots__/problems-script-none-typescript
  tests/__snapshots__/problems-script-vue-typescript
  tests/__snapshots__/syntax-commonjs-none-typescript
  tests/__snapshots__/syntax-commonjs-vue-typescript
  tests/__snapshots__/syntax-esm-none-typescript
  tests/__snapshots__/syntax-esm-react-eslint8.x-typescript
  tests/__snapshots__/syntax-esm-vue-typescript
  tests/__snapshots__/syntax-script-none-typescript
  tests/__snapshots__/syntax-script-vue-typescript
Labels: bug
