Repository eslint/create-config, pull requests merged in 2024-06, with the labels that each got.

#126 fix: enable linting `.jsx` files when React is selected
  lib/config-generator.js
  tests/__snapshots__/problems-esm-react-eslint8.x-javascript
  tests/__snapshots__/problems-esm-react-eslint8.x-typescript
  tests/__snapshots__/problems-esm-react-eslint9.x-javascript
  tests/__snapshots__/problems-esm-react-eslint9.x-typescript
  tests/__snapshots__/syntax-esm-react-eslint8.x-javascript
  tests/__snapshots__/syntax-esm-react-eslint8.x-typescript
  tests/__snapshots__/syntax-esm-react-eslint9.x-javascript
  tests/__snapshots__/syntax-esm-react-eslint9.x-typescript
Labels: bug

#127 refactor: switch to eslint-config-eslint v11
  bin/create-config.js
  eslint.config.js
  lib/config-generator.js
  lib/utils/npm-utils.js
  package.json
  tests/_utils/in-memory-fs.js
  tests/config-snapshots.spec.js
  tests/utils/npm-utils.spec.js
Labels: chore

#130 fix: add files globs to be linted
  lib/config-generator.js
  tests/__snapshots__/config@eslint-config-airbnb
  tests/__snapshots__/problems-commonjs-none-typescript
  tests/__snapshots__/problems-commonjs-vue-javascript
  tests/__snapshots__/problems-commonjs-vue-typescript
  tests/__snapshots__/problems-esm-none-typescript
  tests/__snapshots__/problems-esm-react-eslint8.x-javascript
  tests/__snapshots__/problems-esm-react-eslint8.x-typescript
  tests/__snapshots__/problems-esm-react-eslint9.x-javascript
  tests/__snapshots__/problems-esm-react-eslint9.x-typescript
  tests/__snapshots__/problems-esm-vue-javascript
  tests/__snapshots__/problems-esm-vue-typescript
  tests/__snapshots__/problems-script-none-typescript
  tests/__snapshots__/problems-script-vue-javascript
  tests/__snapshots__/problems-script-vue-typescript
  tests/__snapshots__/syntax-commonjs-none-typescript
  tests/__snapshots__/syntax-commonjs-vue-javascript
  tests/__snapshots__/syntax-commonjs-vue-typescript
  tests/__snapshots__/syntax-esm-none-typescript
  tests/__snapshots__/syntax-esm-react-eslint8.x-javascript
  tests/__snapshots__/syntax-esm-react-eslint8.x-typescript
  tests/__snapshots__/syntax-esm-react-eslint9.x-javascript
  tests/__snapshots__/syntax-esm-react-eslint9.x-typescript
  tests/__snapshots__/syntax-esm-vue-javascript
  tests/__snapshots__/syntax-esm-vue-typescript
  tests/__snapshots__/syntax-script-none-typescript
  tests/__snapshots__/syntax-script-vue-javascript
  tests/__snapshots__/syntax-script-vue-typescript
Labels: bug

#134 chore: output package version
  bin/create-config.js
Labels: accepted, chore

#132 fix: add warning message for ESLint v9 with npm `--force` flag
  lib/config-generator.js
Labels: bug, accepted
