Repository eslint/create-config, pull requests merged in 2025-05, with the labels that each got.

#168 fix: semver calculations for `defineConfig` import
  lib/config-generator.js
  tests/__snapshots__/config@eslint-config-xo
Labels: bug

#167 ci: run tests in Node.js 24
  .github/workflows/ci.yml
Labels: build

#170 fix: ensure posix-compliant newline at end of generated configs
  lib/config-generator.js
  tests/__snapshots__/config@eslint-config-airbnb
  tests/__snapshots__/config@eslint-config-airbnb-base
  tests/__snapshots__/config@eslint-config-standard
  tests/__snapshots__/config@eslint-config-standard-flat
  tests/__snapshots__/config@eslint-config-standard-flat2
  tests/__snapshots__/config@eslint-config-xo
  tests/__snapshots__/empty
  tests/__snapshots__/esm-css-problems
  tests/__snapshots__/esm-css-syntax
  tests/__snapshots__/esm-javascript-json-problems
  tests/__snapshots__/esm-json-problems
  tests/__snapshots__/esm-json-syntax
  tests/__snapshots__/esm-json5-problems
  tests/__snapshots__/esm-json5-syntax
  tests/__snapshots__/esm-jsonc-problems
  tests/__snapshots__/esm-jsonc-syntax
  tests/__snapshots__/esm-markdown-commonmark-problems
  tests/__snapshots__/esm-markdown-commonmark-syntax
  tests/__snapshots__/esm-markdown-gfm-problems
  tests/__snapshots__/esm-markdown-gfm-syntax
  tests/__snapshots__/problems-commonjs-none-javascript
  tests/__snapshots__/problems-commonjs-none-typescript
  tests/__snapshots__/problems-commonjs-react-javascript
  tests/__snapshots__/problems-commonjs-react-typescript
  tests/__snapshots__/problems-commonjs-vue-javascript
  tests/__snapshots__/problems-commonjs-vue-typescript
  tests/__snapshots__/problems-esm-none-javascript
  tests/__snapshots__/problems-esm-none-typescript
  tests/__snapshots__/problems-esm-react-javascript
  tests/__snapshots__/problems-esm-react-typescript
  tests/__snapshots__/problems-esm-vue-javascript
  tests/__snapshots__/problems-esm-vue-typescript
  tests/__snapshots__/problems-script-none-javascript
  tests/__snapshots__/problems-script-none-typescript
  tests/__snapshots__/problems-script-react-javascript
  tests/__snapshots__/problems-script-react-typescript
  tests/__snapshots__/problems-script-vue-javascript
  tests/__snapshots__/problems-script-vue-typescript
  tests/__snapshots__/syntax-commonjs-none-javascript
  tests/__snapshots__/syntax-commonjs-none-typescript
  tests/__snapshots__/syntax-commonjs-react-javascript
  tests/__snapshots__/syntax-commonjs-react-typescript
  tests/__snapshots__/syntax-commonjs-vue-javascript
  tests/__snapshots__/syntax-commonjs-vue-typescript
  tests/__snapshots__/syntax-esm-none-javascript
  tests/__snapshots__/syntax-esm-none-typescript
  tests/__snapshots__/syntax-esm-react-javascript
  tests/__snapshots__/syntax-esm-react-typescript
  tests/__snapshots__/syntax-esm-vue-javascript
  tests/__snapshots__/syntax-esm-vue-typescript
  tests/__snapshots__/syntax-script-none-javascript
  tests/__snapshots__/syntax-script-none-typescript
  tests/__snapshots__/syntax-script-react-javascript
  tests/__snapshots__/syntax-script-react-typescript
  tests/__snapshots__/syntax-script-vue-javascript
  tests/__snapshots__/syntax-script-vue-typescript
  tests/config-snapshots.spec.js
Labels: bug

#173 feat: add support for `.mts` and `.cts` extensions
  lib/config-generator.js
  tests/__snapshots__/problems-commonjs-none-typescript
  tests/__snapshots__/problems-commonjs-react-typescript
  tests/__snapshots__/problems-commonjs-vue-typescript
  tests/__snapshots__/problems-esm-none-typescript
  tests/__snapshots__/problems-esm-react-typescript
  tests/__snapshots__/problems-esm-vue-typescript
  tests/__snapshots__/problems-script-none-typescript
  tests/__snapshots__/problems-script-react-typescript
  tests/__snapshots__/problems-script-vue-typescript
  tests/__snapshots__/syntax-commonjs-none-typescript
  tests/__snapshots__/syntax-commonjs-react-typescript
  tests/__snapshots__/syntax-commonjs-vue-typescript
  tests/__snapshots__/syntax-esm-none-typescript
  tests/__snapshots__/syntax-esm-react-typescript
  tests/__snapshots__/syntax-esm-vue-typescript
  tests/__snapshots__/syntax-script-none-typescript
  tests/__snapshots__/syntax-script-react-typescript
  tests/__snapshots__/syntax-script-vue-typescript
Labels: feature

#176 refactor: combine environment config with base config
  lib/config-generator.js
  tests/__snapshots__/esm-javascript-json-problems
  tests/__snapshots__/problems-commonjs-none-javascript
  tests/__snapshots__/problems-commonjs-none-typescript
  tests/__snapshots__/problems-commonjs-react-javascript
  tests/__snapshots__/problems-commonjs-react-typescript
  tests/__snapshots__/problems-commonjs-vue-javascript
  tests/__snapshots__/problems-commonjs-vue-typescript
  tests/__snapshots__/problems-esm-none-javascript
  tests/__snapshots__/problems-esm-none-typescript
  tests/__snapshots__/problems-esm-react-javascript
  tests/__snapshots__/problems-esm-react-typescript
  tests/__snapshots__/problems-esm-vue-javascript
  tests/__snapshots__/problems-esm-vue-typescript
  tests/__snapshots__/problems-script-none-javascript
  tests/__snapshots__/problems-script-none-typescript
  tests/__snapshots__/problems-script-react-javascript
  tests/__snapshots__/problems-script-react-typescript
  tests/__snapshots__/problems-script-vue-javascript
  tests/__snapshots__/problems-script-vue-typescript
Labels: chore
